Some fixes: - Directing the errors to stderr instead of stdout so it prints the error to terminal instead of maybe to some file. - Quoting some variables inside double quotes just for good practice - Aligning the json so it looks more readable - Removing the echo for printing the content - Addind a check for empty input

diff --git a/ask b/ask
--- a/ask
+++ b/ask
@@ -2,20 +2,19 @@
 
 if [ -z "$ASK_API_URL" ]
 then
-	echo "Environment varible 'ASK_API_URL' is not set"
+	echo "Environment variable 'ASK_API_URL' is not set" >&2
 	exit 1
 fi
 
 if [ -z "$ASK_MODEL" ]
 then
-	echo "Environment varible 'ASK_MODEL' is not set"
+	echo "Environment variable 'ASK_MODEL' is not set" >&2
 	exit 1
 fi
 
-
 if [ -z "$ASK_API_KEY" ]
 then
-	echo "Environment varible 'ASK_API_KEY' is not set"
+	echo "Environment variable 'ASK_API_KEY' is not set" >&2
 	exit 1
 fi
 
@@ -29,21 +28,26 @@ fi
 
 command_arguments=$*
 
-content="$command_arguments $pipe_input"
+content="$command_arguments$pipe_input"
 
-echo $content
+if [[ -z "$content" ]]; then
+    echo "Error. No prompt provided" >&2
+    exit 1
+fi
 
-json=$(jq -n --arg content "$content" '{model:"'"$ASK_MODEL"'", 
+json=$(jq -n 	--arg content "$content" \
+	'{model:"'"$ASK_MODEL"'", 
 		messages: [
 	        	{role: "system", content: "You are a CLI tool. Output plain text only. No yapping. Keep the output concise."},
             		{role: "user", content: $content}
         	]
 	}'
 )
-response=$(curl $ASK_API_URL -s \
+
+response=$(curl "$ASK_API_URL" -s \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASK_API_KEY" \
  -d "$json" 
 )
 
-echo $response | jq -r '.choices[0].message.content'
+echo "$response" | jq -r '.choices[0].message.content'
